{% set name = "tesseract" %}
{% set version = "4.0.0" %}
{% set sha256 = "a1f5422ca49a32e5f35c54dee5112b11b99928fc9f4ee6695cdc6768d69f61dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/tesseract-ocr/{{ name }}/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
    folder: tesseract
  - url: https://github.com/tesseract-ocr/tessdata_fast/archive/4.0.0.tar.gz
    sha256: f1b71e97f27bafffb6a730ee66fd9dc021afc38f318fdc80a464a84a519227fe
    folder: tessdata_fast

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - autoconf
    - pkg-config
    - libtool
  host:
    - libpng
    - jpeg
    - libtiff
    - zlib
    - leptonica
    - libwebp
    - xz
    - openjpeg
    - giflib
  run:
    - libpng
    - jpeg
    - libtiff
    - zlib
    - leptonica
    - libwebp
    - xz
    - openjpeg
    - giflib

test:
  files:
    - eurotext.tif
  commands:
    - tesseract --help
    - tesseract --list-langs
    - tesseract eurotext.tif outputbase

about:
  home: https://github.com/tesseract-ocr/tesseract
  license: Apache-2.0
  license_family: Apache
  license_file: tesseract/LICENSE
  summary: 'An optical character recognition (OCR) engine'

  description: |
    Tesseract is an OCR engine with support for unicode and the ability
    to recognize more than 100 languages out of the box. It can be
    trained to recognize other languages.
  doc_url: https://github.com/tesseract-ocr/tesseract
  dev_url: https://github.com/tesseract-ocr/tesseract

extra:
  recipe-maintainers:
    - CurtLH
    - carlodri
