travis:
  secure:
    BINSTAR_TOKEN: EHby/cuAvU0j28MiUTYAFXdLMX3MrV/RZzS6FAq/lGzwi2Besi6oFL3XhdlV7P/7UqQ5I4TuDKSZ6o7uKa8FvR3DQ3ekuZx5mANxH62CSi6lXzSXMaIFh2BMkUSXZ4yzyggqGa9//y1Goas/5Hdk9W+g1pOoEjfX9hkGk5nsNjw49fNei5PQbiuAtZFIRJob6S2vGiZf6F1cXLEcm0ttKoM+Qq7zO00h0/7GEDc7a0EHQ3cBGr8ULIUFF9xIegq89KJUoOS5jB/+WzlmnuxdGSBiKWjF1nCpslx3n/ZsQhbjIqgH8wjEpr8zsHfIL3l9GK43HQxWs70zysPmyl1Arp6plYJDnuMCpYjmVL0GSM7uG4t0mXQ9GHVvypR6nvJldfpwfhZwplbyjgGs36srnBwgm88w+kCZLkNLEMjrrD5u5C9q/tLt4xvNBLPx52C82FIRdaEobWNgHXvHSUPiNc43V4Se6PNJJSs79SX5PWorrMjIsiYtFp0K0zZj9dEiuJi79zKvG5CB0ixBXykxjCKPfjRuXJX6vW0WeZib6jpXUW51ZbUUdwKtqq80+BpUfbIM3n/RKr1oz0HQkCwdHF7sLZuRPM3C+EbLy3ZKJGHMvcPDNr+kqvzcA4JB6nZi5gifjYLv8iKMkYJBPLkhscti7hcVjA2NCPpyn7X6KfI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
